 @baseUrl = http://localhost:3000/api/v1

### getAProduct /filter
# @name getAProduct
GET {{baseUrl}}/products/filter

### getProducts
# @name getProducts
GET {{baseUrl}}/products/size=2

### getAllProducts
# @name getAllProducts
GET {{baseUrl}}/products

### getCatProd
# @name getCatProd
GET {{baseUrl}}/categories/8/product/209

### getUsers
# @name getUsers
GET {{baseUrl}}/users?limit10&offset=200

### post createProduct
# @name createProduct
POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "camiseta real-madrid",
    "price": 222,
    "image": "http://"
}

### deleteTask
# @name delTask
DELETE {{baseUrl}}/tasks/a2200a42-7104-4ac3-af4b-2af4e4d95199

### update Task
# @name updateTask
PATCH {{baseUrl}}/tasks/1
Content-Type: application/json

{
    "status" : "done"
    //"title":"lavardoneropa",
    //"description": "he bañado a oreo a las 9:25"
}
